DROP TABLE IF EXISTS `zh_mrtb`;
CREATE TABLE `zh_mrtb` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `fbrq` date DEFAULT NULL COMMENT '发布日期',
  `tbrq` date DEFAULT NULL COMMENT '通报日期',
  `qs` varchar(50) DEFAULT NULL COMMENT '期数',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_by` varchar(255) DEFAULT NULL COMMENT '创建人',
  `path` varchar(255) DEFAULT NULL COMMENT '文件路径',
  `chenbanren` varchar(50) DEFAULT NULL COMMENT '承办人',
  `shenheren` varchar(50) DEFAULT NULL COMMENT '审核人',
  `comment1` text,
  `comment2` text,
  `comment3` text,
  `comment4` text,
  `comment5` text,
  `isdel` int(11) DEFAULT '0',
  `totalnum` varchar(50) DEFAULT NULL,
  `num01` varchar(50) DEFAULT NULL COMMENT '刑事警情',
  `num02` varchar(50) DEFAULT NULL COMMENT '治安警情',
  `num03` varchar(50) DEFAULT NULL COMMENT '交通事故',
  `num04` varchar(50) DEFAULT NULL COMMENT '火灾事故',
  `num05` varchar(50) DEFAULT NULL COMMENT '群众求助 ',
  `num06` varchar(50) DEFAULT NULL COMMENT '举报投诉',
  `num08` varchar(50) DEFAULT NULL COMMENT '纠纷',
  `num11` varchar(50) DEFAULT NULL COMMENT '经济案件',
  `num99` varchar(50) DEFAULT NULL COMMENT '其他警情',
  `gq03` varchar(50) DEFAULT NULL,
  `gq02` varchar(50) DEFAULT NULL,
  `gq01` varchar(50) DEFAULT NULL,
  `jy03` varchar(50) DEFAULT NULL,
  `jy02` varchar(50) DEFAULT NULL,
  `jy01` varchar(50) DEFAULT NULL,
  `xh03` varchar(50) DEFAULT NULL,
  `xh02` varchar(50) DEFAULT NULL,
  `xh01` varchar(50) DEFAULT NULL,
  `zx03` varchar(50) DEFAULT NULL,
  `zx02` varchar(50) DEFAULT NULL,
  `zx01` varchar(50) DEFAULT NULL,
  `xs03` varchar(50) DEFAULT NULL,
  `xs02` varchar(50) DEFAULT NULL,
  `xs01` varchar(50) DEFAULT NULL,
  `nsq03` varchar(50) DEFAULT NULL,
  `nsq02` varchar(50) DEFAULT NULL,
  `nsq01` varchar(50) DEFAULT NULL,
  `sjy03` varchar(50) DEFAULT NULL,
  `sjy02` varchar(50) DEFAULT NULL,
  `sjy01` varchar(50) DEFAULT NULL,
  `ys03` varchar(50) DEFAULT NULL,
  `ys02` varchar(50) DEFAULT NULL,
  `ys01` varchar(50) DEFAULT NULL,
  `gd03` varchar(50) DEFAULT NULL,
  `gd02` varchar(50) DEFAULT NULL,
  `gd01` varchar(50) DEFAULT NULL,
  `fx03` varchar(50) DEFAULT NULL,
  `fx02` varchar(50) DEFAULT NULL,
  `fx01` varchar(50) DEFAULT NULL,
  `hss03` varchar(50) DEFAULT NULL,
  `hss02` varchar(50) DEFAULT NULL,
  `hss01` varchar(50) DEFAULT NULL,
  `ym03` varchar(50) DEFAULT NULL,
  `ym02` varchar(50) DEFAULT NULL,
  `ym01` varchar(50) DEFAULT NULL,
  `jw03` varchar(50) DEFAULT NULL,
  `jw02` varchar(50) DEFAULT NULL,
  `jw01` varchar(50) DEFAULT NULL,
  `gz03` varchar(50) DEFAULT NULL,
  `gz02` varchar(50) DEFAULT NULL,
  `gz01` varchar(50) DEFAULT NULL,
  `ch03` varchar(50) DEFAULT NULL,
  `ch02` varchar(50) DEFAULT NULL,
  `ch01` varchar(50) DEFAULT NULL,
  `hs03` varchar(50) DEFAULT NULL,
  `hs02` varchar(50) DEFAULT NULL,
  `hs01` varchar(50) DEFAULT NULL,
  `jd03` varchar(50) DEFAULT NULL,
  `jd02` varchar(50) DEFAULT NULL,
  `jd01` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8;