ALTER TABLE `zh_mrtb`
ADD COLUMN `xsjq01` int DEFAULT 0 AFTER `jd01`,
ADD COLUMN `xsjq02` int DEFAULT 0 AFTER `xsjq01`,
ADD COLUMN `xsjq03` int DEFAULT 0 AFTER `xsjq02`,
ADD COLUMN `xsjq04` int DEFAULT 0 AFTER `xsjq03`,
ADD COLUMN `xsjq05` int DEFAULT 0 AFTER `xsjq04`,
ADD COLUMN `xsjq06` int DEFAULT 0 AFTER `xsjq05`,
ADD COLUMN `xsjq07` int DEFAULT 0 AFTER `xsjq06`,
ADD COLUMN `xsjq08` int DEFAULT 0 AFTER `xsjq07`,
ADD COLUMN `xsjq09` int DEFAULT 0 AFTER `xsjq08`,
ADD COLUMN `xsjq99` int DEFAULT 0 AFTER `xsjq09`;