CREATE TABLE `df_jqzlkh` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `type` varchar(50) DEFAULT NULL,
  `dept` varchar(50) DEFAULT NULL,
  `dept_id` varchar(50) DEFAULT NULL,
  `df_month` varchar(50) DEFAULT NULL,
  `create_by` varchar(50) DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `isdel` int(11) DEFAULT '0',
  `s1` varchar(50) DEFAULT NULL,
  `s2` varchar(50) DEFAULT NULL,
  `s3` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8;

CREATE TABLE `df_qbxx` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `type` varchar(50) DEFAULT NULL,
  `dept` varchar(50) DEFAULT NULL,
  `dept_id` varchar(50) DEFAULT NULL,
  `df_month` varchar(50) DEFAULT NULL,
  `create_by` varchar(50) DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `isdel` int(11) DEFAULT '0',
  `s1` varchar(50) DEFAULT NULL,
  `s2` varchar(50) DEFAULT NULL,
  `s3` varchar(50) DEFAULT NULL,
  `s4` varchar(50) DEFAULT NULL,
  `s5` varchar(50) DEFAULT NULL,
  `s6` varchar(50) DEFAULT NULL,
  `s7` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8;

CREATE TABLE `df_sjfn` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `type` varchar(50) DEFAULT NULL,
  `dept` varchar(50) DEFAULT NULL,
  `dept_id` varchar(50) DEFAULT NULL,
  `df_month` varchar(50) DEFAULT NULL,
  `create_by` varchar(50) DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `isdel` int(11) DEFAULT '0',
  `s1` varchar(50) DEFAULT NULL,
  `s2` varchar(50) DEFAULT NULL,
  `s3` varchar(50) DEFAULT NULL,
  `s4` varchar(50) DEFAULT NULL,
  `s5` varchar(50) DEFAULT NULL,
  `s6` varchar(50) DEFAULT NULL,
  `s7` varchar(50) DEFAULT NULL,
  `s8` varchar(50) DEFAULT NULL,
  `s9` varchar(50) DEFAULT NULL,
  `s10` varchar(50) DEFAULT NULL,
  `s11` varchar(50) DEFAULT NULL,
  `s12` varchar(50) DEFAULT NULL,
  `s13` varchar(50) DEFAULT NULL,
  `s14` varchar(50) DEFAULT NULL,
  `s15` varchar(50) DEFAULT NULL,
  `s16` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=33 DEFAULT CHARSET=utf8;

CREATE TABLE `df_zhzh` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `type` varchar(50) DEFAULT NULL,
  `dept` varchar(50) DEFAULT NULL,
  `dept_id` varchar(50) DEFAULT NULL,
  `df_month` varchar(50) DEFAULT NULL,
  `create_by` varchar(50) DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `isdel` int(11) DEFAULT '0',
  `s1` varchar(50) DEFAULT NULL,
  `s2` varchar(50) DEFAULT NULL,
  `s3` varchar(50) DEFAULT NULL,
  `s4` varchar(50) DEFAULT NULL,
  `s5` varchar(50) DEFAULT NULL,
  `s6` varchar(50) DEFAULT NULL,
  `s7` varchar(50) DEFAULT NULL,
  `s8` varchar(50) DEFAULT NULL,
  `s9` varchar(50) DEFAULT NULL,
  `s10` varchar(50) DEFAULT NULL,
  `s11` varchar(50) DEFAULT NULL,
  `s12` varchar(50) DEFAULT NULL,
  `s13` varchar(50) DEFAULT NULL,
  `s14` varchar(50) DEFAULT NULL,
  `s15` varchar(50) DEFAULT NULL,
  `s16` varchar(50) DEFAULT NULL,
  `s17` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8;