POST http://127.0.0.1:8080/sys/login
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{  "username": "104722",   "password": "111111" }
> {% client.global.set("token", response.body.token); %}

###


#绩效打分报表
GET {{baseUrl}}/report/queryDfData?dfMonth=2020-06&type=1
Accept: */*
Cache-Control: no-cache

#type 1为派出所 2为机关
###

#根据deptId和年月获取当月该单位打分一级项目的分数
GET {{baseUrl}}/df/queryDfDetailByDeptIdAndDate?dfMonth=2020-06&deptId=D0209
Accept: */*
Cache-Control: no-cache

###


#绩效打分报表new
GET {{baseUrl}}/report/queryDfDataNew?dfMonth=2020-06&type=1
Accept: */*
Cache-Control: no-cache

#type 1为派出所 2为机关
###
